version: "3.1"

services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "12345678"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "proyectos@josehumaneshumanes.com"
      PGADMIN_DEFAULT_PASSWORD: "12345678"
      PGADMIN_LISTEN_ADDRESS: "0.0.0.0"
    ports:
      - 5000:80
      - 5050:443
